config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root "companies#index"

  get 'recentworks/:days' => 'works#index'

  get 'timetrackerproject/:slug' => 'projects#show'
  resources :companies
  resources :projects
  resources :works
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  #get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  #
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/company.rb
class Company < ApplicationRecord
  has_many :users
  has_many :projects
  validates :name, length: { minimum: 5}
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :company
  has_many :works
  has_many :users, :through => :works
  validates :name, length: { minimum: 5}
  validates :company, presence: true
  validates :default_rate, numericality: { only_integer: true,greater_than: 50, less_than: 10000 }
  validates :company, presence: true
  validates :slug, uniqueness: true
  validates :slug, length: { minimum: 3 }
  scope :lowdefaultrate, -> { where("default_rate < 100")}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  belongs_to :company
  has_many :works
  has_many :projects, :through => :works
  validates :fname, length: { minimum: 2}
  validates :lname, length: { minimum: 5}
  validates :company, presence: true
end

app/models/work.rb
class Work < ApplicationRecord
  belongs_to :user
  belongs_to :project
  validates :project, presence: true
  validates :user, presence: true
  validates :datetimeperformed, presence: true
  validate :date_is_in_past
  validates :hours, numericality: {only_integer: true,greater_than: 0, less_than_or_equal_to: 8}
  scope :fullday, -> {where("hours >= 8") }
  #scope :recent, -> { where ("datetimeperformed > '#{Time.now - 7.days}'")}

  def self.recentdays(numdaysago)
    since_date = Time.now - numdaysago.to_i.days
    where("datetimeperformed > '#{since_date}'")
  end

  def date_is_in_past
    if datetimeperformed.present? && datetimeperformed > Time.now
      errors.add(:datetimeperformed, "can't be in the future")
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  def index
    @companies = Company.all
  end

  def show
    @company = Company.find(params[:id])
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  def index
    @projects = Project.all
  end

  def show
    if(params[:slug])
      @project = Project.find_by slug: params[:slug]
    else
      @project= Project.find(params[:id])
    end
  end

end

app/controllers/works_controller.rb
class WorksController < ApplicationController
  def index
    if(params[:days])
        @works = Work.recentdays(params[:days]).order('datetimeperformed desc')
    else
       @works = Work.all.order('datetimeperformed desc')
    end
  end

  def show
    @work  = Work.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def user_logged_in_msg
    str = ''
    str +=  '<div class="userloggedin">'
    if user_signed_in?
      str += "<p id=""user_info"">#{current_user}<br>#{link_to('LogOut', destroy_user_session_path, :method => :delete)}</p>"
    else
       str += "<p id=""user_info"">#{link_to('Log In', new_user_session_path)}</p>|#{link_to('Register', new_user_registration_path)}</p>"
    end
    str += '</div>'
    raw(str)
  end


end

app/views/companies/index.html.erb
<h1> Companies: index</h1>

<p> Here are all the companies:</p>

<ul>
  <% @companies.each do |company| %>
    <li><%= link_to company.name, company %></li>
  <% end %>
</ul>

app/views/companies/show.html.erb
<h1><%= @company.name %></h1>
<p><%= link_to 'All Companies', companies_path %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TimeTracker</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application","data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div id="container">
  <header>
    <nav>
      <ul>
        <li><%= link_to 'Companies',companies_path %></li>
        <li><%= link_to 'Projects',projects_path %></li>
        <li><%= link_to 'Works',works_path %></li>
      </ul>
    </nav>
  </header>
  <section id ="main">
    <article>
      <%= yield %>
    </article>
    <aside>
      <%= user_logged_in_msg %>
      <%= yield :aside %>
    </aside>
  </section>
  <footer>
    <p> Time tracker is a <em> Sample Company</em> App</p>
  </footer>
</div>
</body>
</html>

app/views/projects/index.html.erb
<h1> Project: index</h1>

<p> Here are all the projects:</p>

<ul>
  <% @projects.each do |project| %>
    <li><%= link_to project.name, project %></li>
  <% end %>
</ul>

app/views/projects/show.html.erb
<h1><%= @project.name %></h1>

<p> Company: <%= @project.company.name %></p>
<p> Default rate: <%= @project.default_rate %></p>
<p> Slug: <%= @project.slug %></p>
<p><%= link_to 'All Projects', projects_path %></p>

app/views/works/index.html.erb
<h1> Works: index</h1>

<p> Here are all the works:</p>

<ul>
  <% @works.each do |work| %>
    <li><%= link_to work.datetimeperformed, work %></li>
  <% end %>
</ul>

app/views/works/show.html.erb
<h1><%= @work.datetimeperformed %></h1>

<p> User: <%= @work.user.fname %></p>
<p>Project: <%= @work.project.name %></p>
<p>Hours: <%= @work.hours %></p>
<p><%= link_to 'All Works', works_path %></p>